---
title: "Discussion Week 2"
author: "Julia Ferris"
date: "2024-02-01"
output: html_document
---

Suppose that A is a square matrix of size n and $\alpha \in C$ is a scalar. Prove that det ( $\alpha A$ ) = $\alpha^n$ det (A).

Let A = $\begin{bmatrix} a & b \\ c & d \end{bmatrix}$ , n = 2 since the matrix has 2 rows

det ( $\alpha$ $\begin{bmatrix} a & b \\ c & d \end{bmatrix}$ ) = $\alpha^2$ det ( $\begin{bmatrix} a & b \\ c & d \end{bmatrix}$ )

det ( $\begin{bmatrix} \alpha a & \alpha b \\ \alpha c & \alpha d \end{bmatrix}$ ) = $\alpha^2$ \* (ad - bc)

($\alpha$a$\alpha$d) - ($\alpha$b$\alpha$c) = $\alpha^2$ad - $\alpha^2$bc

$\alpha^2$ad - $\alpha^2$bc = $\alpha^2$ad - $\alpha^2$bc

In this proof, you can see that this will be true for square matrices. Alpha would be factored in to the matrix on the left side before finding the determinant. Then, alpha would be multiplied by itself the number of rows of the matrix and then factored in to the product on the right side after finding the determinant. Alpha will be multiplied to each individual value in the matrix on the left, and that is accounted for in the matrix on the right by multiplying alpha by itself multiple times. I provided an example with numbers below since it will make more sense with an actual example. This also shows it works for matrices with more than 2 rows and 2 columns.

Let A = $\begin{bmatrix} 1 & 2 & 3 \\ 5 & 3 & 9 \\ 2 & 1 & 5 \end{bmatrix}$ , n = 3 since the matrix has 3 rows

det ( $\alpha$ $\begin{bmatrix} 1 & 2 & 3 \\ 5 & 3 & 9 \\ 2 & 1 & 5 \end{bmatrix}$ ) = $\alpha^3$ det ( $\begin{bmatrix} 1 & 2 & 3 \\ 5 & 3 & 9 \\ 2 & 1 & 5 \end{bmatrix}$ )

det ( $\begin{bmatrix} \alpha 1 & \alpha 2 & \alpha 3 \\ \alpha 5 & \alpha 3 & \alpha 9 \\ \alpha 2 & \alpha 1 & \alpha 5 \end{bmatrix}$ ) = $\alpha^3$ \* (1\*3\*5 + 2\*9\*2 + 3\*5\*1 - 3\*3\*2 - 1\*1\*9 - 5\*2\*5)

$\alpha 1 \alpha 3 \alpha 5 + \alpha2 \alpha 9 \alpha 2 + \alpha 3 \alpha 5 \alpha 1 - \alpha 3 \alpha 3 \alpha 2 - \alpha 1 \alpha 1 \alpha 9 - \alpha 5 \alpha 2 \alpha 5$ = $\alpha^3$ \* (-11)

$\alpha^3$ \* (1\*3\*5 + 2\*9\*2 + 3\*5\*1 - 3\*3\*2 - 1\*1\*9 - 5\*2\*5) = $\alpha^3$ \* (-11)

$\alpha^3$ \* (-11) = $\alpha^3$ \* (-11)
